# Generated by Django 6.0.5 on 2026-05-21 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ADMIN', 'Admin'), ('ACTUARIAL', 'Actuarial'), ('OPERATIONS', 'Operations'), ('FINANCE', 'Finance & Accounting'), ('HR', 'HR'), ('IT', 'IT'), ('PROVIDERS', 'Providers'), ('MARKETING', 'Marketing'), ('CLAIMS', 'Claims'), ('UNDERWRITING', 'Underwriting')], default='IT', max_length=50)),
                ('is_department_head', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Affected User/Client Name')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(choices=[('ADMIN', 'Admin'), ('ACTUARIAL', 'Actuarial'), ('OPERATIONS', 'Operations'), ('FINANCE', 'Finance & Accounting'), ('HR', 'HR'), ('IT', 'IT'), ('PROVIDERS', 'Providers'), ('MARKETING', 'Marketing'), ('CLAIMS', 'Claims'), ('UNDERWRITING', 'Underwriting')], default='IT', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low (Non-Urgent)'), ('MEDIUM', 'Medium (Standard)'), ('HIGH', 'High (Urgent)'), ('CRITICAL', 'Critical (Emergency)')], default='LOW', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Manager Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not Required (Emergency)')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open (Unassigned)'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved (Pending Feedback)'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Needs Escalation')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='IT Resolution Notes')),
                ('client_feedback_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Client Star Rating')),
                ('client_feedback_notes', models.TextField(blank=True, null=True, verbose_name='Client Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
