# Generated by Django 6.0.5 on 2026-05-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='needs_head_approval',
            field=models.BooleanField(default=True, verbose_name='Needs Dept Head Approval'),
        ),
    ]
