# Generated by Django 6.0.5 on 2026-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='it_tier',
            field=models.CharField(blank=True, choices=[('TIER_1', 'Tier 1 — First Response'), ('TIER_2', 'Tier 2 — Advanced Support')], default='TIER_1', max_length=10, verbose_name='IT Support Tier'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_from_tier',
            field=models.CharField(blank=True, choices=[('TIER_1', 'Tier 1 — First Response'), ('TIER_2', 'Tier 2 — Advanced Support')], max_length=10, null=True, verbose_name='Escalated From Tier'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
    ]
