# Generated by Django 6.0.5 on 2026-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_employeeprofile_it_tier_ticket_escalated_from_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Department Head Instructions'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dispatch_notes',
            field=models.TextField(blank=True, null=True, verbose_name='IT Dispatcher Instructions'),
        ),
    ]
