# Generated by Django 6.0.5 on 2026-06-02 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_approval_notes_ticket_dispatch_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_preventive_maintenance',
            field=models.BooleanField(default=False, verbose_name='Is Preventive Maintenance'),
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Every Day'), ('WEEKLY', 'Every Week'), ('MONTHLY', 'Every Month'), ('QUARTERLY', 'Last Week of Every Quarter'), ('CUSTOM', 'Specific Custom Dates')], max_length=20)),
                ('custom_date_start', models.DateField(blank=True, null=True)),
                ('custom_date_end', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
