# Generated by Django 6.0.5 on 2026-06-03 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_is_preventive_maintenance_recurringtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='dispatch_notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_preventive_maintenance',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_feedback_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_feedback_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='escalated_from_tier',
            field=models.CharField(blank=True, choices=[('TIER_1', 'Tier 1 — First Response'), ('TIER_2', 'Tier 2 — Advanced Support')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='needs_head_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TICKET_APPROVED', 'Your ticket was approved'), ('TICKET_REJECTED', 'Your ticket was rejected'), ('TICKET_RESOLVED', 'Your ticket has been resolved'), ('NEEDS_APPROVAL', 'A ticket needs your approval'), ('TICKET_ASSIGNED_HEAD', 'Your approved ticket was dispatched to IT'), ('TICKET_RESOLVED_HEAD', 'A department ticket was resolved'), ('NEW_TICKET_INCOMING', 'New ticket needs assignment'), ('MAINTENANCE_COMPLETED', 'Preventive maintenance completed'), ('TICKET_RESOLVED_RATED', 'Ticket resolved — rating received'), ('TASK_ASSIGNED', 'A ticket was assigned to you'), ('MAINTENANCE_ANNOUNCED', 'Preventive maintenance announced'), ('FEEDBACK_RECEIVED', 'You received a new feedback rating'), ('TASK_ESCALATED', 'A ticket has been escalated to you')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announced_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RecurringTask',
        ),
    ]
