# Generated by Django 6.0.5 on 2026-06-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_approval_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='announced_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Department Head Instructions'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dispatch_notes',
            field=models.TextField(blank=True, null=True, verbose_name='IT Dispatcher Instructions'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_preventive_maintenance',
            field=models.BooleanField(default=False, verbose_name='Is Preventive Maintenance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_feedback_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Client Comments'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_feedback_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Client Star Rating'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Affected User/Client Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='escalated_from_tier',
            field=models.CharField(blank=True, choices=[('TIER_1', 'Tier 1 — First Response'), ('TIER_2', 'Tier 2 — Advanced Support')], max_length=10, null=True, verbose_name='Escalated From Tier'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False, verbose_name='Needs Escalation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='needs_head_approval',
            field=models.BooleanField(default=True, verbose_name='Needs Dept Head Approval'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True, verbose_name='IT Resolution Notes'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Ticket Number'),
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Every Day'), ('WEEKLY', 'Every Week'), ('MONTHLY', 'Every Month'), ('QUARTERLY', 'Last Week of Every Quarter'), ('CUSTOM', 'Specific Custom Dates')], max_length=20)),
                ('custom_date_start', models.DateField(blank=True, null=True)),
                ('custom_date_end', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PreventiveMaintenance',
        ),
    ]
