# Generated by Django 6.0.5 on 2026-06-03 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_preventivemaintenance_announced_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pm_review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='IT Head Review Notes'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pm_review_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='IT Head PM Review Rating'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pm_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source_recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tickets', to='tickets.recurringtask', verbose_name='Source Recurring Task'),
        ),
    ]
