# Generated by Django 6.0.5 on 2026-06-04 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_pm_review_notes_ticket_pm_review_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('ticket_approved', 'Ticket Approved'), ('ticket_rejected', 'Ticket Rejected'), ('ticket_resolved', 'Ticket Resolved'), ('needs_approval', 'Ticket Needs Approval'), ('ticket_dispatched', 'Ticket Dispatched'), ('needs_assigning', 'Ticket Needs Assigning'), ('pm_finished', 'PM Task Finished'), ('it_resolved', 'IT Staff Resolved Ticket'), ('rating_received', 'IT Staff Got Rated'), ('ticket_assigned', 'Ticket Assigned to You'), ('pm_announced', 'PM Task Posted'), ('feedback_received', 'You Received Feedback'), ('ticket_escalated', 'Ticket Escalated to You')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
