# Generated by Django 6.0.5 on 2026-06-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Times Reopened'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Reopening'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reopened At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ticket_approved', 'Ticket Approved'), ('ticket_rejected', 'Ticket Rejected'), ('ticket_resolved', 'Ticket Resolved'), ('needs_approval', 'Ticket Needs Approval'), ('ticket_dispatched', 'Ticket Dispatched'), ('needs_assigning', 'Ticket Needs Assigning'), ('ticket_reopened', 'Ticket Reopened by Employee'), ('pm_finished', 'PM Task Finished'), ('it_resolved', 'IT Staff Resolved Ticket'), ('rating_received', 'IT Staff Got Rated'), ('ticket_assigned', 'Ticket Assigned to You'), ('pm_announced', 'PM Task Posted'), ('feedback_received', 'You Received Feedback'), ('ticket_escalated', 'Ticket Escalated to You')], max_length=30),
        ),
    ]
