# Generated by Django 6.0.5 on 2026-06-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_escalated_by_ticket_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Issue'), ('SOFTWARE', 'Software / Application'), ('NETWORK', 'Network & Connectivity'), ('ACCOUNT', 'Account & Access'), ('EMAIL', 'Email & Communication'), ('DATA', 'Data & Backup'), ('PERFORMANCE', 'System Performance'), ('NEW_EQUIPMENT', 'New Equipment Request'), ('INSTALLATION', 'Installation / Setup'), ('SECURITY', 'Security Concern'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Request Category'),
        ),
    ]
