# Generated by Django 6.0.5 on 2026-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled End Time'),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled Start Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled End Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled Start Time'),
        ),
    ]
