# Generated by Django 6.0.5 on 2026-06-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_recurringtask_end_time_recurringtask_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtask',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='recurringtask',
            name='start_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='custom_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled End Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled Start Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
