# Generated by Django 6.0.5 on 2026-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_recurringtask_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='custom_date_end',
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
