# Generated by Django 6.0.5 on 2026-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_remove_ticket_custom_date_end_recurringtask_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
    ]
