# Generated by Django 6.0.5 on 2026-06-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticket_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Uppercase slug, e.g. HARDWARE. Must be unique.', max_length=30, unique=True, verbose_name='Category Key')),
                ('label', models.CharField(max_length=100, verbose_name='Display Label')),
                ('icon', models.CharField(default='fa-solid fa-tag', help_text='Space-separated FA classes, e.g. fa-solid fa-desktop', max_length=80, verbose_name='Font Awesome Icon Classes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active (visible on forms)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
